CREATE TABLE game
(id INTEGER NOT NULL,
title VARCHAR(255) NOT NULL,
logo VARCHAR(255),
PRIMARY KEY (id));

CREATE TABLE content
(id INTEGER NOT NULL,
content TEXT NOT NULL,
gameId INTEGER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (gameId) REFERENCES game(id));

CREATE TABLE stats
(id INTEGER NOT NULL,
timestamp INTEGER,
answers INTEGER,
lifelines INTEGER,
gameId INTEGER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (gameId) REFERENCES game(id));